var jsonLang = {
    'ES': {
        'Login': [
            { 'Id': 'txtUser', 'Text': 'Usuario o Email', 'Type': 'placeholder' },
            { 'Id': 'txtPass', 'Text': 'Contraseña', 'Type': 'placeholder' },
            { 'Id': 'imgCaptcha', 'Text': 'Click para generar un nuevo Captcha', 'Type': 'alt' },
            { 'Id': 'txtCaptcha', 'Text': 'Captcha', 'Type': 'placeholder' },
            { 'Id': 'btnLogin', 'Text': '<i class="fas fa-user fa-fw"></i>&nbsp;Ingresar', 'Type': 'html' },
            { 'Id': 'btnSignup', 'Text': 'Registrarse', 'Type': 'placeholder' },
            { 'Id': 'btnSignup', 'Text': '<i class="fas fa-info fa-fw"></i>&nbsp;Registrarse', 'Type': 'html' },
            { 'Id': 'lblWelcome', 'Text': 'Bienvenido a <strong className="font-weight-bold">ECOPETROL</strong>', 'Type': 'html'},
            { 'Id': 'lblLanguage', 'Text': 'Lenguaje', 'Type': 'html'},
            { 'Id': 'lblRememberPassword', 'Text': 'Recordar Contraseña', 'Type': 'html' },
            { 'Id': 'lblRememberPassword2', 'Text': 'Recordar Contraseña', 'Type': 'html' },
            { 'Id': 'lblNIT', 'Text': 'NIT', 'Type': 'html' },
            { 'Id': 'lblEmail', 'Text': 'Correo Electrónico', 'Type': 'html' },
            { 'Id': 'lblRememberText', 'Text': 'Por favor diligenciar la siguiente información para restablecer su contraseña', 'Type': 'html' },
        ],
        'Register': [
            { 'Id': 'lblRegistrationForm', 'Text': '<strong className="font-weight-bold darkGreen">Formulario de Registro</strong>', 'Type': 'html' },
            { 'Id': 'lblContactName', 'Text': 'Nombre Completo', 'Type': 'html' },
            { 'Id': 'lblPhoneNumber', 'Text': 'Número de Teléfono', 'Type': 'html' },
            { 'Id': 'lblEmail', 'Text': 'Correo Electrónico', 'Type': 'html' },
            { 'Id': 'lblProponentType', 'Text': 'Tipo de Proponente', 'Type': 'html' },
            { 'Id': 'lblNIT', 'Text': 'NIT', 'Type': 'html' },
            { 'Id': 'lblBusinessName', 'Text': 'Razón Social', 'Type': 'html' },
            { 'Id': 'lblWebSite', 'Text': 'Página Web', 'Type': 'html' },
            { 'Id': 'lblSIPROEOption', 'Text': '¿Tiene SIPROE?', 'Type': 'html' },
            { 'Id': 'lblSIPROECode', 'Text': 'Código  SIPROE', 'Type': 'html' },
            { 'Id': 'lblTechnologyName', 'Text': 'Nombre de la Tecnología', 'Type': 'html' },
            { 'Id': 'lblTechnologyObject', 'Text': 'Objeto de la Tecnología', 'Type': 'html' },
            { 'Id': 'lblFunctionality', 'Text': 'Funcionalidad', 'Type': 'html' },
            { 'Id': 'lblValuePromise', 'Text': 'Promesa de Valor', 'Type': 'html' },
            { 'Id': 'lblApplicationSegment', 'Text': 'Segmento de Aplicación', 'Type': 'html' },
            { 'Id': 'lblSpecificApplicationArea', 'Text': 'Área Específica de Aplicación', 'Type': 'html' },
            { 'Id': 'lblMaturityLevel', 'Text': 'Nivel de Madurez', 'Type': 'html' },
            { 'Id': 'btnNext', 'Text': 'Siguiente', 'Type': 'html' },
            { 'Id': 'btnBack', 'Text': 'Volver', 'Type': 'html' },
            { 'Id': 'btnPrevious', 'Text': 'Atrás', 'Type': 'html' },
            { 'Id': 'btnSend', 'Text': 'Enviar', 'Type': 'html' },
            { 'Id': 'lblAttachInformation', 'Text': 'Adjuntar Información', 'Type': 'html' },
            { 'Id': 'lblTechnologyInformation', 'Text': 'Información de la Tecnología', 'Type': 'html' },
            { 'Id': 'lblPersonalinformation', 'Text': 'Información Personal', 'Type': 'html' },
            { 'Id': 'lblBusinessInformation', 'Text': 'Información de la Compañía', 'Type': 'html' },
            { 'Id': 'opcSpanish', 'Text': 'Español', 'Type': 'html' },
            { 'Id': 'opcEnglish', 'Text': 'Ingles', 'Type': 'html' },
            { 'Id': 'opcMaker', 'Text': 'Fabricante', 'Type': 'html' },
            { 'Id': 'opcDistributor', 'Text': 'Distribuidor', 'Type': 'html' },
            { 'Id': 'opcYes', 'Text': 'Si', 'Type': 'html' },
            { 'Id': 'opcExploration', 'Text': 'Exploración', 'Type': 'html' },
            { 'Id': 'opcProduction', 'Text': 'Producción', 'Type': 'html' },
            { 'Id': 'opcTransport', 'Text': 'Transporte', 'Type': 'html' },
            { 'Id': 'opcRefination', 'Text': 'Refinación', 'Type': 'html' },
            { 'Id': 'opcComercialization', 'Text': 'Comercialización', 'Type': 'html' },
            { 'Id': 'lblLanguage', 'Text': 'Lenguaje', 'Type': 'html'},
            { 'Id': 'lblState', 'Text': 'Estado', 'Type': 'html'},
            { 'Id': 'lblState2', 'Text': 'Estado', 'Type': 'html'},
            { 'Id': 'lvlCompany', 'Text': 'Empresa', 'Type': 'html'},
            { 'Id': 'lblTec', 'Text': 'Tecnología', 'Type': 'html'},
            { 'Id': 'lblDate', 'Text': 'Fecha de Presentación', 'Type': 'html'},
            { 'Id': 'lblSegment', 'Text': 'Segmento', 'Type': 'html'},
            { 'Id': 'lblArea', 'Text': 'Área de Aplicación', 'Type': 'html'},
            { 'Id': 'lblProposal', 'Text': 'Información de la Propuesta', 'Type': 'html'},
            { 'Id': 'lblProp', 'Text': 'Propuesta:', 'Type': 'html'},
            { 'Id': 'lblReactivation', 'Text': 'Reactivación:', 'Type': 'html'},
            { 'Id': 'lblJustification', 'Text': 'Justificación para la Reactivación:', 'Type': 'html'},
            { 'Id': 'btnReactivate', 'Text': 'Reactivar', 'Type': 'html'},
            { 'Id': 'btnReactivate2', 'Text': 'Reactivar', 'Type': 'html' },
            { 'Id': 'pVer', 'Text': 'Ver', 'Type': 'html' },
            { 'Id': 'pRegisterForm', 'Text': 'Continuar', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl1', 'Text': 'Investigación científica básica y se da inicio a la transición a la investigación Aplicada.  En esta fase se cuenta solo con formulaciones matemáticas o algoritmos del principio básico.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl2', 'Text': 'Formulación del concepto, aplicación y puesta en práctica. Se diseña un plan de desarrollo, estudios y pequeños experimentos.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl3', 'Text': 'Pruebas analíticas, pruebas de concepto, pruebas de laboratorio orientadas a demostrar la factibilidad técnica de los conceptos tecnológicos.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl4', 'Text': 'Tecnología prototipo construido en laboratorio y en un entorno controlado que determine el potencial de ampliación.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl5', 'Text': 'Tecnología lista para ser usada en la simulación de un entorno real, y se ha identificado aspectos de seguridad, limitaciones ambientales y/o regulatorios entre otros.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl6', 'Text': 'Tecnología prototipo capaz de desarrollar todas las funciones requeridas por un sistema operativo en condiciones muy cercanas a las que se espera vaya a funcionar (industrial).', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl7', 'Text': 'Tecnología que opera a escala pre-comercial, se han perfeccionado la evaluación del ciclo de vida y evolución económica. Se realiza primera corrida piloto y pruebas reales finales.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl8', 'Text': 'La tecnología ha sido probada a nivel comercial y cuenta con manuales para el uso y mantenimiento del producto.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl9', 'Text': 'La tecnología está probada y disponible para su comercialización.', 'Type': 'html' },
            { 'Id': 'lblAttach', 'Text': 'Adjuntar', 'Type': 'html' },
            { 'Id': 'pMadurez', 'Text': 'Marque una de las siguientes opciones en la cual usted considera que se encuentra la tecnología que propone y adjunte los respectivos soportes. <br>Su tecnología se encuentra en:', 'Type': 'html' },
            { 'Id': 'pAttach', 'Text': 'NOTA: Los soportes que se recomienda adjuntar, entre otros pueden ser: comercialización y/o producción de su tecnología disponible para el mercado, casos de éxito documentados de la tecnología, implementaciones (cantidad) de la tecnología a nivel Nacional o internacional (preferiblemente vigentes), área y/o campo de aplicación de la tecnología (país, compañía, año, sector, etc) factores diferenciadores y/o ventajas competitivas de su tecnología, cómo ha evolucionado su tecnología, certificados de patentes (si aplica), etc', 'Type': 'html' },
            { 'Id': 'txtTechnologyName', 'Text': 'Mencione el nombre exacto de la tecnología propuesta. (200 caracteres)', 'Type': 'placeholder' },
            { 'Id': 'txtTechnologyObject', 'Text': 'Explique brevemente para qué está concebida la tecnología. (500 caracteres)', 'Type': 'placeholder' },
            { 'Id': 'txtFunctionality', 'Text': 'Explique brevemente el principio básico de la tecnología propuesta. (1.000 caracteres)', 'Type': 'placeholder' },
            { 'Id': 'txtValuePromise', 'Text': 'Cuantifique o describa los beneficios por la implementación de la tecnología propuesta. (1.000 caracteres)', 'Type': 'placeholder' },
        ],
        'SideBar': [
            { 'Id': 'pRegister', 'Text': 'Registro', 'Type': 'html' },
            { 'Id': 'pHome', 'Text': 'Inicio', 'Type': 'html' },
            { 'Id': 'pConsult', 'Text': 'Consultar', 'Type': 'html' },
            { 'Id': 'pFormGNTF17', 'Text': 'Formulario T&I-F-002', 'Type': 'html' },
            { 'Id': 'pLogout', 'Text': 'Cerrar Sesión', 'Type': 'html' }, 
            { 'Id': 'pLanguage', 'Text': 'Lenguaje', 'Type': 'html' },
        ],
        'FormGNTF17':[
            { 'Id': 'opcYes', 'Text': 'Si', 'Type': 'html' },
            { 'Id': 'FormNombreTec', 'Text': 'Nombre dado a la tecnología y principales características técnicas (puntos clave, modo de operación, elementos principales, etc.) ', 'Type': 'html' },
            { 'Id': 'FormCompatibilidadPros', 'Text': '¿La tecnología ofrecida es compatible con los procesos productivos del negocio o industria del petróleo y gas?', 'Type': 'html' },
            { 'Id': 'FormCompatibilidadSI', 'Text': '¿Esta tecnología requiere compatibilidad con sistemas de información para operar? ', 'Type': 'html' },
            { 'Id': 'FormSolProblComun', 'Text': '¿Esta tecnología puede solucionar problemas comunes que se presentan en el negocio o en la Industria del Petróleo y Gas?  ', 'Type': 'html' },
            { 'Id': 'FormHomologa', 'Text': '¿Esta tecnología, se ajusta a las normas generales o específicas que permitan homologar aspectos técnicos y operativos de los procesos en los que podría intervenir? ', 'Type': 'html' },
            { 'Id': 'FormRespNecesidad', 'Text': '¿Responde a una necesidad no cubierta de la Industria del Petróleo y Gas? ', 'Type': 'html' },
            { 'Id': 'FormVentajasDesventajas', 'Text': '¿Podría describir las ventajas o desventajas que su tecnología presenta frente a otras tecnologías de aplicación similar? (Anexar la información que corresponda)', 'Type': 'html' },
            { 'Id': 'FormEmpresasRecUso', 'Text': '¿Qué empresas o personas han recomendado el uso de la tecnología ofrecida? (Anexar la información que corresponda). ', 'Type': 'html' },
            { 'Id': 'FormUsuariosPotenciales', 'Text': 'Indique los potenciales usuarios de la tecnología dentro del negocio o de la Industria del Petróleo y Gas. ', 'Type': 'html' },
            { 'Id': 'FormOtrosProcesos', 'Text': 'Especifique otros usos o procesos productivos o de apoyo, a los que podría beneficiar la tecnología ofrecida. ', 'Type': 'html' },
            { 'Id': 'lblIndicaciones', 'Text': '<b>En relación con la tecnología que ofrece, especifique otras indicaciones técnicas potenciales a tener en cuenta dentro del negocio o de la Industria del Petróleo y Gas, como:</b>', 'Type': 'html' },
            { 'Id': 'FormDificultades', 'Text': 'Problemas o dificultades que se podrían presentar con la aplicación de la tecnología ofrecida. (Especifique posible afectación del proceso productivo, utilice evidencias de otras empresas donde se ha aplicado la tecnología). ', 'Type': 'html' },
            { 'Id': 'FormAspectos', 'Text': 'Aspectos a tener en cuenta durante el desarrollo del proceso productivo de la Industria del Petróleo y Gas con la aplicación de la tecnología ofrecida. ', 'Type': 'html' },
            { 'Id': 'lblBeneficios', 'Text': '<b>Beneficios potenciales con la aplicación o implementación de la tecnología ofrecida:</b>', 'Type': 'html' },
            { 'Id': 'FormDentroProcesos', 'Text': 'Dentro de un proceso productivo del negocio. ', 'Type': 'html' },
            { 'Id': 'FormParaNegocio', 'Text': 'Para el negocio o Empresa. ', 'Type': 'html' },
            { 'Id': 'FormRiesgos', 'Text': 'Riesgos potenciales por la aplicación de la tecnología para la empresa, (Especifique posible afectación del proceso productivo, utilice evidencias de otras empresas donde se ha aplicado la tecnología). ', 'Type': 'html' },
            { 'Id': 'FormDisponibilidad', 'Text': '¿Cuál es la disponibilidad y capacidad de prestar apoyo técnico del oferente de la tecnología? (Explique las necesidades de disponibilidad y capacidad de su personal) ', 'Type': 'html' },
            { 'Id': 'FormVisitas', 'Text': '¿Será suficiente contar con visitas periódicas o se requerirá la presencia del técnico a tiempo completo durante los meses iniciales? (Justifique, en cualquier caso) ', 'Type': 'html' },
            { 'Id': 'FormDisponibilidadEstudios', 'Text': '¿Existe disponibilidad de estudios de calidad que considere aportan pruebas o evidencias sobre los beneficios y los riesgos asociados a la tecnología ofrecida? (Pruebas industriales, aplicación industrial, ensayos de laboratorio, otros relacionados con la industria de petróleo y gas). ', 'Type': 'html' },
            { 'Id': 'FormEvidencia', 'Text': '¿hay evidencias relacionadas con alguna revisión sistemática o informe de evaluación realizado sobre la tecnología ofrecida o similares, que considere de buena calidad? (Estudios de evaluación económica, tipo costo-efectividad, costo-utilidad, etc.). ', 'Type': 'html' },
            { 'Id': 'FormIndicadores', 'Text': 'En los estudios anteriores, ¿qué medidas o qué indicadores considera más relevantes para la tecnología ofrecida? (ej. reducción del riesgo relativo, vida útil de la tecnología, ahorros comprobables, etc.). Especificar los resultados más importantes, tanto desde el punto de vista del proceso como del producto, y adjunte o referencie el estudio. ', 'Type': 'html' },
            { 'Id': 'FormResultadosAplicables', 'Text': '¿Son los resultados de los estudios anteriores aplicables a Ecopetrol y a la Industria del Petróleo y Gas? ', 'Type': 'html' },
            { 'Id': 'FormFactoresModificar', 'Text': '¿Qué factores podrían modificar, estos resultados en las condiciones de la operación normal del negocio de ECOPETROL, con la aplicación de la tecnología ofrecida? (Características operativas diferentes respecto a los estudios, efectos de la curva de aprendizaje, aceptabilidad, adaptabilidad y/o expectativas del negocio, etc.) ', 'Type': 'html' },
            { 'Id': 'FormMejorarICPPruebasWebFront', 'Text': '¿La aplicación de la tecnología ofrecida podría mejorar índices de productividad, eficiencia, calidad, otros? (adicionales al reemplazo o sustitución de tecnologías maduras u obsoletas). (Anexar cálculos que permitan comparar) ', 'Type': 'html' },
            { 'Id': 'lblModificaciones', 'Text': '<b>Tipo de modificaciones físicas o estructurales requeridas para implantar la tecnología ofrecida: </b>', 'Type': 'html' },
            { 'Id': 'FormCambioProductivo', 'Text': '¿Es necesario realizar cambios en el flujo normal del proceso productivo?.  ', 'Type': 'html'},
            { 'Id': 'FormAdicionarPersonal', 'Text': '¿Se requiere adicionar personal especializado, o personas que trabajan en este tipo de procesos requieren aumentar su nivel de formación? (Defina el nivel de especialización o formación sugerido, si es posible las horas de formación requeridas). ', 'Type': 'html'},
            { 'Id': 'FormNecesidadMantenimiento', 'Text': 'Explique las necesidades de mantenimiento que requiere la tecnología ofrecida.  ', 'Type': 'html'},
            { 'Id': 'FormInventarioSuficiente', 'Text': '¿Especifique si cuenta con un inventario suficientemente amplio de repuestos e insumos necesarios para la operación de la tecnología?  ', 'Type': 'html'},
            { 'Id': 'FormProcedimientoInterno', 'Text': '¿Se requieren procedimientos internos en la empresa para garantizar la calidad de los resultados de la tecnología ofrecida? (Explique brevemente y en lo posible incluya protocolos e indicadores de evaluación y seguimiento). ', 'Type': 'html'},
            { 'Id': 'FormCambioOperacion', 'Text': '¿Cuáles serían los cambios sustanciales que se pueden esperar en los indicadores de la operación o de productividad?, (tenga en cuenta reducción en tiempo de operación, supervisión, mantenimiento, otros). ', 'Type': 'html'},
            { 'Id': 'FormImplicaciones', 'Text': '¿La tecnología ofrecida puede generar algunas implicaciones de consideración para los operarios, derivados de la aplicación de la tecnología?, (como molestias físicas, calidad de vida, afectaciones de la piel, dolencias, otras). ', 'Type': 'html'},
            { 'Id': 'lblImplicacionLegal', 'Text': '<b>Implicación de aspectos legales, éticos o ambientales. </b>', 'Type': 'html'},
            { 'Id': 'FormAfectaMedioAmbiente', 'Text': '¿Durante la operación de la tecnología ofrecida, que aspectos podrían considerarse que pudieran afectar negativa o positivamente el medio ambiente? (por ejemplo residuos, entre otros) ', 'Type': 'html'},
            { 'Id': 'FormConsecuenciaMABaja', 'Text': '¿Cuáles podrían ser las consecuencias en el medio ambiente al dar de baja la tecnología ofrecida? (Explique las que se han considerado hasta el momento). ', 'Type': 'html'},
            { 'Id': 'FormPropiedadIntelectual', 'Text': '¿De quién es la propiedad intelectual de la tecnología ofrecida?. En caso de que la propiedad corresponda a una empresa o persona diferente al oferente, esplique su relación de propiedad. ', 'Type': 'html'},
            { 'Id': 'FormEstadosTramites', 'Text': 'En caso de que no se tenga la propiedad intelectual de la tecnología ofrecida, explique: ¿En qué estado se encuentran los trámites relacionados con la Propiedad Intelectual para la tecnología ofrecida? (Explique las solicitudes que se han realizado hasta el momento). ', 'Type': 'html'},
            { 'Id': 'FormAspectosProtegibles', 'Text': '¿Cuáles aspectos relacionados con la Propiedad intelectual de la tecnología ofrecida, considera que pueden ser protegibles? (Procedimientos, productos, procesos, servicios, marcas, diseños, trazados otros. Anexar conceptos de fuentes consultadas). ', 'Type': 'html'},
            { 'Id': 'FormNegociacionPropiedad', 'Text': '¿Habría la posibilidad de negociación de la Propiedad Intelectual en caso de que Ecopetrol apoyado en su capacidad de investigación y desarrollo realice adaptaciones, mejoras u otros a la tecnología ofrecida? ', 'Type': 'html'},
            { 'Id': 'btnNext', 'Text': 'Siguiente', 'Type': 'html' },
            { 'Id': 'btnBack', 'Text': 'Volver', 'Type': 'html' },
            { 'Id': 'btnPrevious', 'Text': 'Atrás', 'Type': 'html' },
            { 'Id': 'btnSend', 'Text': 'Enviar', 'Type': 'html' },
            { 'Id': 'lblCompatibilidad', 'Text': '<b>Compatibilidad Tecnológica:</b>', 'Type': 'html' },
            { 'Id': 'lblAplicabilidad', 'Text': '<b>Aplicabilidad de la tecnología:</b>', 'Type': 'html' },
            { 'Id': 'lblForm', 'Text': '<strong className="font-weight-bold darkGreen">T&I-F-002 Formato Detallado de Formulación de Propuestas Tecnológicas</strong>', 'Type': 'html' },
            { 'Id': 'lblDescripcion', 'Text': 'I. Descripción de la tecnología ofrecida', 'Type': 'html' },
            { 'Id': 'lblCaracteristicas', 'Text': 'II. Características Técnicas', 'Type': 'html' },
            { 'Id': 'lblEvidencia', 'Text': 'III. Evidencia sobre eficacia, efectividad Y seguridad', 'Type': 'html' },
            { 'Id': 'lblEfectos', 'Text': 'IV. Efectos en el negocio - empresa', 'Type': 'html' },
            { 'Id': 'lblEstado', 'Text': 'V. Estado de la propiedad intelectual de la tecnologia ofrecida', 'Type': 'html' },
            { 'Id': 'lblAdjuntar', 'Text': 'Adjuntar Informacion', 'Type': 'html' },
            { 'Id': 'lblNote', 'Text': '<i><u>Gracias por la presentación voluntaria de esta información. <br></br>Le recordamos que el diligenciamiento de este formato, así como el análisis por parte de Ecopetrol de esta información, no compromete a Ecopetrol, ni a su Grupo Empresarial o a algún funcionario de éstas, a tomar alguna decisión positiva o a iniciar procedimientos contractuales con respecto a la tecnología presentada o a su Compañía. </u></i>', 'Type': 'html' },
            { 'Id': 'btnDesist', 'Text': 'Desistir', 'Type': 'html' },
            { 'Id': 'btnDesist2', 'Text': 'Desistir', 'Type': 'html' },
            { 'Id': 'lblReason', 'Text': 'Motivo', 'Type': 'html' },
            { 'Id': 'lblDesist', 'Text': 'Desistir', 'Type': 'html' },
            { 'Id': 'lblCompletionInstructions', 'Text': 'Instrucciones de diligenciamiento:', 'Type': 'html' },
            {'Id': 'lblInstructions', 'Text': '<b>1.</b>Este Formato solicita información genérica para un rango amplio de tecnologías, lo que puede ocasionar que algunas preguntas no sean aplicables a la propuesta; lo anterior deja a disposición del proponente, anexar la información que crea conveniente en los espacios especificados para tal fin.</br> <b>2.</b>Si considera ambigüedad o múltiples interpretaciones en alguno de los términos utilizados en el Formato, utilice las definiciones técnicas que considere pertinente, lo cual lo obliga a realizar las aclaraciones respectivas.En caso de utilizar abreviaturas defina su significado.</br> <b>3.</b>En caso de que alguno de los datos solicitados no esté disponible en el momento, hágalo constar en el anexo respectivo y explique cuando va a obtener la información.', 'Type': 'html' },
            { 'Id': 'lblProponent', 'Text': 'Proponente', 'Type': 'html' },
            { 'Id': 'lblPresentedBy', 'Text': 'Presentada Por', 'Type': 'html' },
            { 'Id': 'lblEmail', 'Text': 'Correo Electrónico', 'Type': 'html' },
            { 'Id': 'lblPosition', 'Text': 'Cargo:', 'Type': 'html' },
            { 'Id': 'idCelphoneNumber', 'Text': 'Número de Celular', 'Type': 'html' },
            { 'Id': 'lblAddress', 'Text': 'Dirección', 'Type': 'html' },
            { 'Id': 'lblAddress2', 'Text': 'Dirección', 'Type': 'html' },
            { 'Id': 'lblPhoneFax', 'Text': 'Teléfono/FAX', 'Type': 'html' },
            { 'Id': 'lblTechnologyName', 'Text': 'Nombre de la Tecnologia', 'Type': 'html' },
            { 'Id': 'lblRequest', 'Text': 'Solicitud de Evaluación de Tecnología', 'Type': 'html' },
            { 'Id': 'lblRequestDate', 'Text': 'Fecha de solicitud de evaluación', 'Type': 'html' },
            { 'Id': 'lblAdvisors', 'Text': 'Asesores', 'Type': 'html' },
            { 'Id': 'lblArea', 'Text': 'Área', 'Type': 'html' },
            { 'Id': 'lblAttachInformation', 'Text': 'Adjuntar Información', 'Type': 'html' },
            { 'Id': 'lblAttach', 'Text': 'Adjuntar', 'Type': 'html.' },
        ],
    },
    'EN': {
        'Login': [
            { 'Id': 'txtUser', 'Text': 'User or Email', 'Type': 'placeholder' },
            { 'Id': 'txtPass', 'Text': 'Password', 'Type': 'placeholder' },
            { 'Id': 'imgCaptcha', 'Text': 'Click para generar un nuevo Captcha', 'Type': 'alt' },
            { 'Id': 'txtCaptcha', 'Text': 'Captcha', 'Type': 'placeholder' },
            { 'Id': 'btnLogin', 'Text': '<i class="fas fa-user fa-fw"></i>&nbsp;Login', 'Type': 'html' },
            { 'Id': 'btnSignup', 'Text': 'Sign Up', 'Type': 'placeholder' },
            { 'Id': 'btnSignup', 'Text': '<i class="fas fa-info fa-fw"></i>&nbsp;Register', 'Type': 'html' },
            { 'Id': 'lblWelcome', 'Text': 'Welcome to <strong className="font-weight-bold">ECOPETROL</strong>', 'Type': 'html'},
            { 'Id': 'lblLanguage', 'Text': 'Language', 'Type': 'html' },
            { 'Id': 'lblRememberPassword', 'Text': 'Remember Password', 'Type': 'html' },
            { 'Id': 'lblRememberPassword2', 'Text': 'Remember Password', 'Type': 'html' },
            { 'Id': 'lblEmail', 'Text': 'Email', 'Type': 'html' },
            { 'Id': 'lblNIT', 'Text': 'SSN', 'Type': 'html' },
            { 'Id': 'lblRememberText', 'Text': 'Please fill out the following information to reset your password', 'Type': 'html' },
        ],
        'Register': [
            { 'Id': 'lblRegistrationForm', 'Text': '<strong className="font-weight-bold darkGreen">Registration Form</strong>', 'Type': 'html' },
            { 'Id': 'lblContactName', 'Text': 'Full Name (Contact Name)', 'Type': 'html' },
            { 'Id': 'lblPhoneNumber', 'Text': 'Phone Number', 'Type': 'html' },
            { 'Id': 'lblEmail', 'Text': 'Email', 'Type': 'html' },
            { 'Id': 'lblProponentType', 'Text': 'Proponent Type', 'Type': 'html' },
            { 'Id': 'lblNIT', 'Text': 'Social Security Number', 'Type': 'html' },
            { 'Id': 'lblBusinessName', 'Text': 'Business Name', 'Type': 'html' },
            { 'Id': 'lblWebSite', 'Text': 'WebSite', 'Type': 'html' },
            { 'Id': 'lblSIPROEOption', 'Text': 'Do You have SIPROE?', 'Type': 'html' },
            { 'Id': 'lblSIPROECode', 'Text': 'SIPROE Code', 'Type': 'html' },
            { 'Id': 'lblTechnologyName', 'Text': 'Technology Name', 'Type': 'html' },
            { 'Id': 'lblTechnologyObject', 'Text': 'Technology Object', 'Type': 'html' },
            { 'Id': 'lblFunctionality', 'Text': 'Funcionality', 'Type': 'html' },
            { 'Id': 'lblValuePromise', 'Text': 'Value Promise', 'Type': 'html' },
            { 'Id': 'lblApplicationSegment', 'Text': 'Application Segment', 'Type': 'html' },
            { 'Id': 'lblSpecificApplicationArea', 'Text': 'Specific Application Area', 'Type': 'html' },
            { 'Id': 'lblMaturityLevel', 'Text': 'Maturity Level', 'Type': 'html' },
            { 'Id': 'btnNext', 'Text': 'Next', 'Type': 'html' },
            { 'Id': 'btnBack', 'Text': 'Back', 'Type': 'html' },
            { 'Id': 'btnPrevious', 'Text': 'Previous', 'Type': 'html' },
            { 'Id': 'btnSend', 'Text': 'Send', 'Type': 'html' },
            { 'Id': 'lblAttachInformation', 'Text': 'Attach Information', 'Type': 'html' },
            { 'Id': 'lblTechnologyInformation', 'Text': 'Technology Information', 'Type': 'html' },
            { 'Id': 'lblPersonalinformation', 'Text': 'Personal Information', 'Type': 'html' },
            { 'Id': 'lblBusinessInformation', 'Text': 'Business Information', 'Type': 'html' },
            { 'Id': 'opcSpanish', 'Text': 'Spanish', 'Type': 'html' },
            { 'Id': 'opcEnglish', 'Text': 'English', 'Type': 'html' },
            { 'Id': 'opcMaker', 'Text': 'Maker', 'Type': 'html' },
            { 'Id': 'opcDistributor', 'Text': 'Distributor', 'Type': 'html' },
            { 'Id': 'opcYes', 'Text': 'Yes', 'Type': 'html' },
            { 'Id': 'opcExploration', 'Text': 'Exploration', 'Type': 'html' },
            { 'Id': 'opcProduction', 'Text': 'Production', 'Type': 'html' },
            { 'Id': 'opcTransport', 'Text': 'Transport', 'Type': 'html' },
            { 'Id': 'opcRefination', 'Text': 'Refination', 'Type': 'html' },
            { 'Id': 'opcComercialization', 'Text': 'Comercialization', 'Type': 'html' },
            { 'Id': 'lblLanguage', 'Text': 'Language', 'Type': 'html'},
            { 'Id': 'lblState', 'Text': 'State', 'Type': 'html'},
            { 'Id': 'lblState2', 'Text': 'State', 'Type': 'html'},
            { 'Id': 'lvlCompany', 'Text': 'Company', 'Type': 'html'},
            { 'Id': 'lblTec', 'Text': 'Technology', 'Type': 'html'},
            { 'Id': 'lblDate', 'Text': 'Date of presentation', 'Type': 'html'},
            { 'Id': 'lblSegment', 'Text': 'Segment', 'Type': 'html'},
            { 'Id': 'lblArea', 'Text': 'Aplication Area', 'Type': 'html'},
            { 'Id': 'lblProposal', 'Text': 'Proposal Information', 'Type': 'html'},
            { 'Id': 'lblProp', 'Text': 'Proposal', 'Type': 'html'},
            { 'Id': 'lblReactivation', 'Text': 'Reactivation', 'Type': 'html'},
            { 'Id': 'lblJustification', 'Text': 'Justification for reactivation', 'Type': 'html'},
            { 'Id': 'btnReactivate', 'Text': 'Reactivate', 'Type': 'html'},
            { 'Id': 'btnReactivate2', 'Text': 'Reactivate', 'Type': 'html' },
            { 'Id': 'pVer', 'Text': 'View', 'Type': 'html' },
            { 'Id': 'pRegisterForm', 'Text': 'Continue', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl1', 'Text': 'Basic scientific research and the transition to Applied research begins. In this phase, there are only mathematical formulations or algorithms of the basic principle.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl2', 'Text': 'Concept formulation, application and implementation. A development plan, studies and small experiments are designed.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl3', 'Text': 'Analytical tests, proofs of concept, laboratory tests aimed at demonstrating the technical feasibility of technological concepts.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl4', 'Text': 'Prototype technology built in the laboratory and in a controlled environment that determines the potential for expansion.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl5', 'Text': 'Technology ready to be used in the simulation of a real environment, and aspects of safety, environmental and / or regulatory limitations, among others, have been identified.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl6', 'Text': 'Prototype technology capable of developing all the functions required by an operating system under very advanced conditions that are expected to work (industrial).', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl7', 'Text': 'Technology that operates on a pre-commercial scale, life cycle assessment and economic evolution have been refined. First pilot run and final real tests are carried out.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl8', 'Text': 'The technology has been commercially tested and has manuals for the use and maintenance of the product.', 'Type': 'html' },
            { 'Id': 'opcMaturityLvl9', 'Text': 'The technology is tested and available for conversion.', 'Type': 'html' },
            { 'Id': 'lblAttach', 'Text': 'Attach', 'Type': 'html' },
            { 'Id': 'pMadurez', 'Text': 'Check one of the following options in which you consider the proposed technology to be found and attach the specific supports. <br> Its technology is in:', 'Type': 'html' },
            { 'Id': 'pAttach', 'Text': 'NOTE: The supports that are recommended to be attached, among others, may be: commercialization and/or production of your technology available for the market, documented success stories of the technology, implementations (quantity) of the technology at the National or international level (preferably in force ), area and/or field of application of the technology (country, company, year, sector, etc.) differentiating factors and/or competitive advantages of its technology, how its technology has evolved, patent certificates (if applicable), etc. ', 'Type': 'html' },
            { 'Id': 'txtTechnologyName', 'Text': 'Mention the exact name of the proposed technology. (200 characters)', 'Type': 'placeholder' },
            { 'Id': 'txtTechnologyObject', 'Text': 'Briefly explain what the technology is designed for. (500 characters)', 'Type': 'placeholder' },
            { 'Id': 'txtFunctionality', 'Text': 'Briefly explain the basic principle of the proposed technology. (1000 characters)', 'Type': 'placeholder' },
            { 'Id': 'txtValuePromise', 'Text': 'Quantify or describe the benefits of implementing the proposed technology. (1000 characters)', 'Type': 'placeholder' },
            { 'Id': 'tpSegment', 'Text': 'Quantify or describe the benefits of implementing the proposed technology. (1000 characters)', 'Type': 'html' },
        ],
        'SideBar': [
            { 'Id': 'pRegister', 'Text': 'Register', 'Type': 'html' },
            { 'Id': 'pHome', 'Text': 'Home', 'Type': 'html' },
            { 'Id': 'pConsult', 'Text': 'Consult', 'Type': 'html' },
            { 'Id': 'pFormGNTF17', 'Text': 'T&I-F-002 Form', 'Type': 'html' },
            { 'Id': 'pLogout', 'Text': 'Logout', 'Type': 'html' },
            { 'Id': 'pLanguage', 'Text': 'Language', 'Type': 'html' },
        ],
        'FormGNTF17':[
            { 'Id': 'opcYes', 'Text': 'Yes', 'Type': 'html' },
            { 'Id': 'FormNombreTec', 'Text': 'Name given to the technology and main technical characteristics (key points, mode of operation, main elements, etc.)', 'Type': 'html' },
            { 'Id': 'FormCompatibilidadPros', 'Text': 'Is the technology offered compatible with the productive processes of the Oil and Gas Industry or business?', 'Type': 'html' },
            { 'Id': 'FormCompatibilidadSI', 'Text': 'Does this technology require compatibility with information systems to operate?', 'Type': 'html' },
            { 'Id': 'FormSolProblComun', 'Text': 'Can this technology solve common problems that arise in the business or Industry of Oil and Gas?', 'Type': 'html' },
            { 'Id': 'FormHomologa', 'Text': 'Does this technology conform to the general or specific norms that allow homologating technical and operational aspects of the processes in which it could intervene?', 'Type': 'html' },
            { 'Id': 'FormRespNecesidad', 'Text': 'Does it respond to an unmet need of the Oil and Gas Industry?', 'Type': 'html' },
            { 'Id': 'FormVentajasDesventajas', 'Text': 'Could you describe the advantages or disadvantages of your technology compared to other similar application technologies? (Attach the corresponding information)', 'Type': 'html' },
            { 'Id': 'FormEmpresasRecUso', 'Text': 'Which companies or people have recommended the use of the technology offered? (Attach the corresponding information)', 'Type': 'html' },
            { 'Id': 'FormUsuariosPotenciales', 'Text': 'Indicate the potential users of the technology within the business or the Oil and Gas Industry.', 'Type': 'html' },
            { 'Id': 'FormOtrosProcesos', 'Text': 'Specify other productive or supportive uses or processes, to which the offered technology could benefit.', 'Type': 'html' },
            { 'Id': 'lblIndicaciones', 'Text': '<b>In relation to the technology it offers, specify other potential technical indications to take into account within the business or the Oil and Gas Industry, such as:</b>', 'Type': 'html' },
            { 'Id': 'FormDificultades', 'Text': 'Problems or difficulties that could arise with the application of the offered technology. (Specify possible impact on the production process, use evidence from other companies where the technology has been applied).', 'Type': 'html' },
            { 'Id': 'FormAspectos', 'Text': 'Aspects to take into account during the development of the production process of the Oil and Gas Industry with the application of the technology offered.', 'Type': 'html' },
            { 'Id': 'lblBeneficios', 'Text': '<b>Potential benefits with the application or implementation of the technology offered:</b>', 'Type': 'html' },
            { 'Id': 'FormDentroProcesos', 'Text': 'Within a productive business process', 'Type': 'html' },
            { 'Id': 'FormParaNegocio', 'Text': 'For the business or company', 'Type': 'html' },
            { 'Id': 'FormRiesgos', 'Text': 'Potential risks from the application of technology to the company, (Specify possible impact on the production process, use evidence from other companies where the technology has been applied)', 'Type': 'html' },
            { 'Id': 'FormDisponibilidad', 'Text': 'What is the availability and ability to provide technical support from the technology provider? (Explain the availability and capacity needs of your staff)', 'Type': 'html' },
            { 'Id': 'FormVisitas', 'Text': 'Will it be enough to have periodic visits or will the presence of the technician be required full time during the initial months? (Justify, in any case)', 'Type': 'html' },
            { 'Id': 'FormDisponibilidadEstudios', 'Text': 'Is there availability of quality studies that you consider provide evidence about the benefits and risks associated with the technology offered? (Industrial tests, industrial application, laboratory tests, others related to the oil and gas industry)', 'Type': 'html' },
            { 'Id': 'FormEvidencia', 'Text': 'Is there evidence related to any systematic review or evaluation report carried out on the technology offered or similar, that you consider of good quality? (Economic evaluation studies, cost-effectiveness type, cost-utility, etc.).', 'Type': 'html' },
            { 'Id': 'FormIndicadores', 'Text': 'In previous studies, what measures or indicators do you consider most relevant to the technology offered? (example: reduction of relative risk, useful life of technology, verifiable savings, etc.).Specify the most important results, both from the point of view of the process and the product, and attach or reference the study.', 'Type': 'html' },
            { 'Id': 'FormResultadosAplicables', 'Text': 'Are the results of previous studies applicable to Ecopetrol and the Oil and Gas Industry?', 'Type': 'html' },
            { 'Id': 'FormFactoresModificar', 'What factors could modify, these results in the conditions of the normal operation of the business of ECOPETROL, with the application of the offered technology? (Different operational characteristics regarding studies, effects of the learning curve, acceptability, adaptability and / or business expectations, etc.)': 'Full Name:', 'Type': 'html' },
            { 'Id': 'FormMejorarICPPruebasWebFront', 'Text': 'Could the application of the offered technology improve productivity, efficiency, quality indices, others? (additional to the replacement or replacement of mature or obsolete technologies). (Attach calculations that allow comparison)', 'Type': 'html' },
            { 'Id': 'lblModificaciones', 'Text': '<b>Type of physical or structural modifications required to implement the technology offered:</b>', 'Type': 'html' },
            { 'Id': 'FormCambioProductivo', 'Text': 'Is it necessary to make changes in the normal flow of the production process?', 'Type': 'html'},
            { 'Id': 'FormAdicionarPersonal', 'Text': 'Do you need to add specialized personnel, or do people who work in these types of processes need to increase their level of training? (Define the level of specialization or training suggested, if possible the required training hours)', 'Type': 'html'},
            { 'Id': 'FormNecesidadMantenimiento', 'Text': 'Explain the maintenance needs required by the technology offered.', 'Type': 'html'},
            { 'Id': 'FormInventarioSuficiente', 'Text': 'Specify if you have a sufficiently large inventory of spare parts and supplies necessary for the operation of the technology?', 'Type': 'html'},
            { 'Id': 'FormProcedimientoInterno', 'Text': 'Are internal procedures required in the company to guarantee the quality of the results of the technology offered? (Explain briefly and if possible include evaluation and monitoring protocols and indicators).', 'Type': 'html'},
            { 'Id': 'FormCambioOperacion', 'Text': 'What would be the substantial changes that can be expected in the operation or productivity indicators? (Consider reduction in operation time, supervision, maintenance, others)', 'Type': 'html'},
            { 'Id': 'FormImplicaciones', 'Text': 'Can the technology offered generate some implications for operators, derived from the application of technology ?, (such as physical discomfort, quality of life, skin problems, medical conditions, others)', 'Type': 'html'},
            { 'Id': 'lblImplicacionLegal', 'Text': '<b>Involvement of legal, ethical or environmental aspects</b>', 'Type': 'html'},
            { 'Id': 'FormAfectaMedioAmbiente', 'Text': 'During the operation of the offered technology, what aspects could be considered that could affect the environment negatively or positively? (for example waste, among others)', 'Type': 'html'},
            { 'Id': 'FormConsecuenciaMABaja', 'Text': 'What could be the consequences on the environment by canceling the technology offered? (Explain those that have been considered so far).', 'Type': 'html'},
            { 'Id': 'FormPropiedadIntelectual', 'Text': 'Whose intellectual property is the technology offered? In case the property corresponds to a company or person other than the offeror, explain your property relationship', 'Type': 'html'},
            { 'Id': 'FormEstadosTramites', 'Text': 'If you do not have the intellectual property of the technology offered, explain: In what state are the procedures related to Intellectual Property for the technology offered? (Explain the requests that have been made so far)', 'Type': 'html'},
            { 'Id': 'FormAspectosProtegibles', 'Text': 'What aspects related to the intellectual property of the technology offered, do you consider that they can be protected? (Procedures, products, processes, services, brands, designs, other paths. Attach concepts from consulted sources)', 'Type': 'html'},
            { 'Id': 'FormNegociacionPropiedad', 'Text': 'Would there be the possibility of negotiating Intellectual Property in case Ecopetrol, based on its research and development capacity, makes adaptations, improvements or others to the technology offered?', 'Type': 'html'},
            { 'Id': 'btnNext', 'Text': 'Next', 'Type': 'html' },
            { 'Id': 'btnBack', 'Text': 'Back', 'Type': 'html' },
            { 'Id': 'btnPrevious', 'Text': 'Previous', 'Type': 'html' },
            { 'Id': 'btnSend', 'Text': 'Send', 'Type': 'html' },
            { 'Id': 'lblCompatibilidad', 'Text': '<b>Technological Compatibility:</b>', 'Type': 'html' },
            { 'Id': 'lblAplicabilidad', 'Text': '<b>Applicability of the technology:</b>', 'Type': 'html' },
            { 'Id': 'lblForm', 'Text': '<strong className="font-weight-bold darkGreen">T&I-F-002 Detailed Form for Formulation of Technological Proposals</strong>', 'Type': 'html' },
            { 'Id': 'lblDescripcion', 'Text': 'I. Description of the technology offered', 'Type': 'html' },
            { 'Id': 'lblCaracteristicas', 'Text': 'II. Technical characteristics', 'Type': 'html' },
            { 'Id': 'lblEvidencia', 'Text': 'III. Evidence of effectiveness, effectiveness and safety', 'Type': 'html' },
            { 'Id': 'lblEfectos', 'Text': 'IV. Effects on business - company', 'Type': 'html' },
            { 'Id': 'lblEstado', 'Text': 'V. Intellectual property status of the technology offered', 'Type': 'html' },
            { 'Id': 'lblAdjuntar', 'Text': 'Attach Information', 'Type': 'html' },
            { 'Id': 'lblNote', 'Text': '<i><u>Thank you for the voluntary presentation of this information. <br> </br> We remind you that the completion of this format, as well as the analysis by Ecopetrol of this information, does not commit Ecopetrol, its Business Group or any assistance officer, to make any positive decision or to initiate contractual procedures regarding the technology presented or your Company.</u></i>', 'Type': 'html' },
            { 'Id': 'btnDesist', 'Text': 'Desist', 'Type': 'html' },
            { 'Id': 'btnDesist2', 'Text': 'Desist', 'Type': 'html' },
            { 'Id': 'lblReason', 'Text': 'Reason', 'Type': 'html' },
            { 'Id': 'lblDesist', 'Text': 'Desist', 'Type': 'html' },
            { 'Id': 'lblCompletionInstructions', 'Text': 'Diligence Instructions:', 'Type': 'html' },
            { 'Id': 'lblInstructions', 'Text': '<b>1. </b> This Format requests generic information for a wide range of technologies, which may result in some questions not being applicable to the proposal; The foregoing makes available to the proponent, append the information it deems appropriate in the spaces specified for this purpose. <br><b> 2. </b> If you consider ambiguity or multiple interpretations in any of the terms used In the Format, use the technical definitions that you consider pertinent, which forces you to make the respective clarifications.In case of using abbreviations define their meaning. <br> <b> 3. </b> In case that some of the requested data is not available at the moment, please state it in the respective annex and explain when you will obtain the information.', 'Type': 'html' },
            { 'Id': 'lblProponent', 'Text': 'Proponent', 'Type': 'html' },
            { 'Id': 'lblPresentedBy', 'Text': 'Presented By', 'Type': 'html' },
            { 'Id': 'lblEmail', 'Text': 'Email', 'Type': 'html' },
            { 'Id': 'lblPosition', 'Text': 'Position', 'Type': 'html' },
            { 'Id': 'idCelphoneNumber', 'Text': 'Celphone Number', 'Type': 'html' },
            { 'Id': 'lblAddress', 'Text': 'Address', 'Type': 'html' },
            { 'Id': 'lblAddress2', 'Text': 'Address', 'Type': 'html' },
            { 'Id': 'lblPhoneFax', 'Text': 'Phone Number/FAX', 'Type': 'html' },
            { 'Id': 'lblTechnologyName', 'Text': 'Technology Name', 'Type': 'html' },
            { 'Id': 'lblRequest', 'Text': 'Technology Evaluation Request', 'Type': 'html' },
            { 'Id': 'lblAdvisors', 'Text': 'Advisors', 'Type': 'html' },
            { 'Id': 'lblRequestDate', 'Text': 'Evaluation Request Date', 'Type': 'html' },
            { 'Id': 'lblArea', 'Text': 'Area', 'Type': 'html' },
            { 'Id': 'lblAttachInformation', 'Text': 'Attach Information', 'Type': 'html' },
            { 'Id': 'lblAttach', 'Text': 'Attach', 'Type': 'html.' },
            
        ],
    }
}
export default jsonLang;
